version: 2
jobs:
  tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: install
          command: sudo python setup.py install && sudo ./dev/install-dev.sh
      - run:
          name: flake8
          command: flake8
      - run:
          name: test
          command: pytest --cov
      - run:
          name: validate
          command: agilekit git validate
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: install
          command: sudo python setup.py install sdist bdist_wheel
      - run:
          name: upload release
          command: twine upload dist/* --username lsbardel --password $PYPI_PASSWORD
      - run:
          name: create tag
          command: agilekit git release --yes


workflows:
  version: 2
  build-deploy:
    jobs:
      - tests
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: deploy
            tags:
              ignore: /.*/
